### ISSUE TITLE
Downloaded pdf, ppt etc. capture scroll bar

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [RevealBi/Reveal.Sdk#248] opened 2024-08-08 10:18 UTC
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

while downloading pdf report scroll bar is visible in pdf its not looking good

**Comment by brianlagunas** [comment] 2024-08-08 14:47
This is by design. Images are created by taking a screenshot of the RevealView. This will include all visual elements including the scrollbar. Can you provide an image of an example of what you are seeing so we can verify that it falls within the expected results? Are you referring to scrollbars on the dashboard or on an individual visualization?

I'm closing as by-design for now, but if you provide more information that indicates a bigger issue is occurring, we can reopen and re-evaluate.

**Closed by brianlagunas** 2024-08-08 14:47 UTC
Labels: :bug: bug, :art: status: by-design

**Comment by elaiyaraja-marimuthu** [comment] 2024-08-09 04:40
Hi Sunil,
Please reply to this email  and attach screenshot.


Thanks,

Elaiyaraja Marimuthu

Assistant Director

Tel +91.9751921236 | Mobile +91.7904388794

Email ***@***.******@***.***>

Acuity Knowledge Partners | www.acuitykp.com<http://www.acuitykp.com/>

Embassy Tech Village 1, Building 2A, Phase 2, East Wing

Third Floor, Outer Ring Road, Devarabeesanahalli, Varthur Hobli

Bangalore East Taluk 560 087, India



________________________________

**Comment by elaiyaraja-marimuthu** [comment] 2024-08-09 10:38
Hi Nitin,

I would like to address a few concerns regarding our current processes:

Defect Creation in GitHub:

What is the purpose of creating defects in GitHub without seeking any clarification?
most of the tickets are being closed prematurely. Before closing any ticket, if you need additional information, please write to us and then proceed to close the ticket.

Scroll Bar in PDF or Documents:

Is displaying a scroll bar in PDFs or any documents considered good practice?

Issue Reporting in Discord:

We have been posting a lot of issues in the Discord channel, but we are not receiving enough information in response.
Additionally, we are still using an old version of Reveal BI its not working in AWS build  already we shared logs but they need always more information please schedule call with technical guys to resolve this. Despite continuously posting in the Discord channel, there has been no resolution.
Please address these concerns at your earliest convenience.

We discussed eariler @sunil attached  some excel sheets to create charts but still  we did n't receive any reply  its blocking for us for client requirements.



Thanks,

Elaiyaraja Marimuthu

Assistant Director

Tel +91.9751921236 | Mobile +91.7904388794

Email ***@***.******@***.***>

Acuity Knowledge Partners | www.acuitykp.com<http://www.acuitykp.com/>

Embassy Tech Village 1, Building 2A, Phase 2, East Wing

Third Floor, Outer Ring Road, Devarabeesanahalli, Varthur Hobli

Bangalore East Taluk 560 087, India



________________________________
