### ISSUE TITLE
[BUG]: Percentage type value is not showing the correct graph.

### ISSUE THREAD

**Issue by kathswa1** [RevealBi/Reveal.Sdk#262] opened 2024-08-22 05:28 UTC
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

The percentage type value is not giving the correct graph 
**Steps to reproduce:-**

- created currency line item.
- created percentage line item.
- input the same value in perc and currency  line items for eg (-12.56)
- when using combination of percentage and number line items both  together to create  graph
- Then observed the percentage graph is still showing at 0 but the value is -12.56. 

 **actual result-** 
- when I am using percentage type for line item, 
- then the value is getting converted to percentage, 
- but the graph represented is incorrect. 

**expected result -** 
- when I am using the percentage type for line item. 
- then the value and graph both should update and show the value correctly. 

![image](https://github.com/user-attachments/assets/aeb85c02-be7d-4dae-940e-888d5e92225a)
![image](https://github.com/user-attachments/assets/0ed3e312-31c4-4a0c-a740-5cde835e49df)

**Comment by TorreyBetts** [comment] 2024-08-22 10:48
What you're seeing is by design. The first value field is what is considered the first series when internally processing the returned data. This first series will create both axes and that numeric y axis will be used for the other value fields.

Since your first series was specified as percentage, it's using percents for the numeric y axis labels. The second series' first value of -12.56 is technically `-12.56*100 = -1256`, which is the correct location on the scale used.

**Comment by Remmei** [comment] 2024-08-22 12:35
what about the second screenshot. Percentage value is -13% but in the chart , bar for Percentage value is showing incorrect

**Comment by TorreyBetts** [comment] 2024-08-22 12:50
In the second image the first value column is using the regular number formatting so the percentage value will use that scale. The label says -13%, with that we can reverse it to `-13/100 = 0.13`, which falls in line with its location.

**Comment by Remmei** [comment] 2024-08-22 14:04
Here is use case :  we have two fields Revenue ( currency type)  and Growth Margin (percentage type) .  In which we want to show report of both Revenue and Growth Margin in the chart with respective scale. Then , what type of chart is preferred to create

**Comment by TorreyBetts** [comment] 2024-08-22 14:15
It may be worth looking at the Combo visualization, that visualization creates an axis on the left and right side which will help differentiate the different number types you have. I'm closing this issue as it's by design, if you have any further concerns or issues, feel free to open this back up.

**Closed by TorreyBetts** 2024-08-22 14:15 UTC
Labels: :bug: bug, :art: status: by-design

**Comment by Remmei** [comment] 2024-09-03 05:51
HI @TorreyBetts , 
we tried using combo ( bar & line) chart for representing two different number types . One thing we observed when it is number is negative , the line chart is giving wrong visualization.
![image (2)](https://github.com/user-attachments/assets/9eea5245-0d75-4d39-8f43-4b8b70e6aa60)
<img width="884" alt="image (1)" src="https://github.com/user-attachments/assets/378eb98f-bb20-48a0-9681-94f02f0f6165">
