### ISSUE TITLE
Ability To Sort Month Labels Along a Chart Axis in Correct Date Order, Not Alphabetically

### ISSUE THREAD

**Issue by Aerobird88** [RevealBi/Reveal.Sdk#102] opened 2023-10-05 17:31 UTC
**Is your feature request related to a problem? Please describe.**
I have a number of panels that show year over year comparisons by Month.  The months sort alphabetically which is not correct.

**Describe the solution you'd like**
I need the ability to sort by Month Name in January-December order

**Describe alternatives you've considered**
No alternatives known

**Additional context**
![image](https://github.com/RevealBi/Reveal.Sdk/assets/147091264/186c3634-ab05-48a5-baee-eec7ac7c4706)

**Comment by TorreyBetts** [comment] 2023-10-05 17:45
I'd imagine the sorting isn't correct because those aren't proper date fields? Normally, you'd see the sorting work like below.
<img width="607" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/5093679/eec4110d-33c7-45c7-bfe9-b9d139c11b20">

**Comment by Aerobird88** [comment] 2023-10-05 17:54
I was asked by Brian Lagunes a while back to put in a feature request for this, as to do the year over year comparison, I was have to use MonthName(date_field) function and categorize that by year to get it to overlay multiple years.  I think it’s looking at the MonthName() as a string, and sorting it alphabetically.

Thanks Torrey!

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by Aerobird88** [comment] 2023-10-05 17:54
One other thing to note – I would like to force a Jan thru Dec order, not start with the current month.

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by brianlagunas** [comment] 2023-10-05 18:16
@Aerobird88 I don't remember the context behind this request, but let's first determine what you're trying to do, what data types you are using, and then see if there is already a way to accomplish what you want.

If you are using the monthName function as a calculated field, you can fix the sorting by setting the "Sort by" on the settings of the field

<img width="516" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/835562/7bfcb9fe-50d4-4e4c-b4e8-6fb6cdaf1daa">

sorting before changing the setting:

<img width="787" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/835562/75326824-4e63-46a0-8213-cb7f7d81f2af">


results of setting the sorting:

<img width="947" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/835562/fc84a692-c79a-4d01-b41c-1d19267a7278">


Also, please do not request multiple features in a single issue. Otherwise it will get lost.

**Comment by Aerobird88** [comment] 2023-10-05 18:21
Brian,

I hope you’re doing well – this goes back to an issue we discussed briefly in June.

I tried to go in and update the field settings - I don’t have the same options when I go into the field settings for the calculated field:

***@***.***

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by brianlagunas** [comment] 2023-10-05 19:02
You have to set the "Sorting" to ascending first, then the "Sort by" will appear. To get your desired design, you might need to add the year as a Category as well.

**Comment by Aerobird88** [comment] 2023-10-05 19:35
Here is how I have this setup:

***@***.***
When I do as you suggested and select a sort in that field, I do get the option to then Sort by the underlying date field:

***@***.***

However, when I click “Update Field”, it errors out:

***@***.***

Where do I go from here?

Thanks guys!

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by brianlagunas** [comment] 2023-10-05 19:56
Without more detailed information, we are unable to help. If you feel you have run into a bug, please submit a new issue as a bug and provide as much information as possible. Even providing the actual dashboard file would be helpful.

I am closing this request since we already have this functionality.

**Closed by brianlagunas** 2023-10-05 19:56 UTC
Labels: :toolbox: feature-request

**Comment by Aerobird88** [comment] 2023-10-05 20:05
What other detailed information can I provide?  I know you have to operate a certain way Brian, and I don’t want to cause an issue here or be aggravating to anyone.  Perhaps some background would be helpful here.

Let me give you a brief rundown of my situation:


  *   I am not a programmer.  I do not know anything about coding.
  *   I am a data analyst, primarily developing in SQL and SSRS up to this point.
  *   My employer has adopted Reveal to build winforms dashboards to integrate into our ERP system (more info at www.inxsql.com<http://www.inxsql.com>)
  *   I am quickly being caught in the middle here – my employer has a lot of expectations based on the demos done, but I am not finding a way to accomplish much in Reveal outside of having to write code that I don’t know how to write.  I need some assistance with a development tool, or what information I need to provide to the programmers at my software company here to break the logjam.
  *   Discord is a very confusing way to handle tech support.  I am not trying to spam the message boards with questions, but I need some direction here.

Hopefully this gives you some perspective.  I appreciate everyone’s time and help, and realize I am probably out of place in this developer community not being an actual developer myself.  I understand needing to close out the new feature request if this feature exists, and I can file a bug report, but in general I need some direction on how to use Reveal without programming knowledge.  What do I need to lean on a programmer for, vs what can I develop myself in a GUI or end user environment?

Thanks all,

***@***.***
Michael White
Data Analyst at INxSQL Software

Phone 877-446-9775
Web www.inxsql.com<http://www.inxsql.com/>  Email ***@***.******@***.***>
1117 S Cass Lake Rd, Waterford, MI 48328


*Please note our email policy change below*
INxSQL will no longer send any banking or ACH information via email. If you require this information, please call our office directly. Please be cautious of any emailed banking information you receive from anyone, and always call to confirm numbers prior to sending funds electronically.

**Comment by brianlagunas** [comment] 2023-10-05 20:25
@Aerobird88 I can understand the position you are in. While the Reveal SDK is a developer tool, it also has an end-user aspect to it. This is the area in which we lack the most information to help end-user learn how to use the RevealView from their perspective. We currently do not have user docs, but you can use try using the Slingshot docs as a guide for end-user docs (https://www.slingshotapp.io/en/help/docs/analytics/my-analytics). Not everything will be the same because Slingshot is a custom application that has used the Reveal SDK and customized it to fit their needs. However, there should be enough information to get you going in the right direction.

As far as reporting bugs. The most important thing we need is the error message. Then we need the steps you took to reproduce the issue. A sample dashboard will go a long way in helping us see what went wrong. Information about the data and the data types you are using. Screenshots of the Editor, the error, or anything else they may help us see what the problem could be.

Discord is a great way to provide support since it gives you direct access to the development team, and an instant feedback loop instead of going back and forth through email. Discord also allows you to jump into a screen share session to demo your issues. I would encourage you to become familiar with Discord and use it when you feel you need it.
