### ISSUE TITLE
[BUG]: Column Charts with Categories don't properly map <null> to <null or empty> for filter values in linked dashboards

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#233] opened 2024-07-11 18:21 UTC
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

This is confirmed by Diego and he likely has better working examples.  If you have a parent dashboard with a Column viz and that column viz is categorized and one of the values in a category is null and you create a link to another dashboard that has a filter for the value being charted in the column viz, then the column viz doesn't map `<null>` to `<null or empty>`.  This results in the linked dashboard's filter getting set to `<null>` which is invalid and results in no data being presented on the linked dashboard.

**Comment by dpazos-infragistics** [comment] 2024-07-17 15:06
The issue happens because null and empty are treated the same for a dashboard filter, but when categorization is added to a bar chart, empty string and null values end up in separate categories.
This causes it that when you click the bar for null values and try to navigate to the child dashboard, the value used to perform the link is just "<null>", but the dashboard filter in the child dashboard only has "<null or empty>" which of course, doesn't match.
I'm attaching two test dashboards that reproduce the scenario.
[Dashboard linking.zip](https://github.com/user-attachments/files/16267570/Dashboard.linking.zip)
The dashboards depend on a SQL Server DS with Id "msSqlId" and a DSI with ID "msSqlCustQueryDsItemId" with the following custom query:
"SELECT * FROM (VALUES (1, 'Yes'), (2, 'No'), (3, null)) a(SomeID, Answer)"

**Comment by PVillarmarzo** [comment] 2024-08-28 14:57
This issue has been fixed and will be released in an upcoming release.

**Closed by PVillarmarzo** 2024-08-28 14:57 UTC
Labels: :bug: bug, :white_check_mark: status: resolved
