### ISSUE TITLE
[BUG]: Stacked Columns not rendering properly

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [RevealBi/Reveal.Sdk#240] opened 2024-07-22 14:46 UTC
### SDK Version

1.6.7

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

Stacked Column charts with categories aren't rendering properly. 

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/1c525c88-b591-4401-b5cd-020cedb5f811">

The above screenshot shows a stacked column chart with a category specified.  You can see not all values are being rendered.  

<img width="1588" alt="image" src="https://github.com/user-attachments/assets/741267cf-289a-459a-a38b-17ba934effaf">

However, if you use a stacked bar, as shown in the above screenshot, everything renders properly.

**Comment by brianlagunas** [comment] 2024-07-22 14:50
Does this appear to be the same as #236?

**Comment by brianlagunas** [comment] 2024-07-29 14:34
This is a duplicate of #236. Please follow the issue to get updates on it's progress.

**Closed by brianlagunas** 2024-07-29 14:34 UTC
Labels: :bug: bug, duplicate
