### ISSUE TITLE
[BUG]: Reveal not using our font-family aymore

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#77] opened 2023-08-31 16:27 UTC
### Company

N/A

### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

Java

### Description

Previously (v1.4.0), Reveal used the font we had configured in our application, in thhis case is our font `AvenirNextLTPro`:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/d4bf6196-3905-4182-85ce-39de37f451be)

After upgrading to 1.6.0, I see Reveal is using another font:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/229018ec-98f8-40a7-b01e-bbf0b9897d42)

Looking at the DevTools, I see previously, Reveal's spans had the right font-family:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/bbffe238-dd7f-47bf-bf60-a544d54b2886)

But now, there are some quotes being introduced as part of the font-family:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/d1b692bb-f7ce-451e-8069-529afa5ce1f8)

Quotes are ok around each alternative font name, but not around whole font-family, as the space and comma are going to be interpreted as part of the font's name: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by TorreyBetts** [comment] 2023-08-31 17:23
It's not obvious how you're loading the font or using it. Here's some example code to show how we loaded a custom font.

```
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
  <script src="https://dl.revealbi.io/reveal/libs/1.6.0/infragistics.reveal.js"></script>
  <script>
    async function setupReveal() {
        console.log('setup');

        $.ig.RevealSdkSettings.setBaseUrl(
            'https://samples.revealbi.io/upmedia-backend/reveal-api/'
        );
        $.ig.RevealSdkSettings.theme = createCustomTheme();
        await $.ig.RevealSdkSettings.ensureFontsLoaded();
        console.log('fonts loaded', $.ig.RevealSdkSettings.theme.regularFont);

        var dashboard = await $.ig.RVDashboard.loadDashboard('Sales');
        let revealView = new $.ig.RevealView('#revealView');
        revealView.dashboard = dashboard;
    }

    //create the custom theme
    function createCustomTheme() {
        var theme = new $.ig.RevealTheme();

        const font = 'Libre Baskerville';
        theme.regularFont = font;
        theme.mediumFont = font;
        theme.boldFont = font;

        return theme;
    }

    function loadFonts() {
        document.fonts.load("16px 'Libre Baskerville'").then((ev) => {
          console.log("Fonts loaded:", ev);
          setupReveal();
        });
    }

    const fonts = document.createElement('link');
    fonts.href =
        'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;500;600;700';
    fonts.rel = 'stylesheet';
    document.head.appendChild(fonts);
    fonts.addEventListener('load', loadFonts);
  </script>
  <style>
    #revealView {
        height: 100vh;
        width: 100%;
        border: 2px solid red;
    }
  </style>
</head>
<body style="font-family: 'Libre Baskerville'">
  <div id="revealView"></div>
</body>
</html>
```

**Comment by brianlagunas** [comment] 2023-08-31 17:49
I was able to replicate this. Any font that has a space will have the `&quot;` appended to the begging and end of the font. Looks like something may be escaping it unexpectedly. We'll look into it.

Thanks for reporting this issue.

**Comment by TorreyBetts** [comment] 2023-09-13 15:05
The issue wrote up about the `&quot;` entity is not a bug. We internally use single quotes and the browser interprets in its own way. For example, if you load up webpage using a font that contains a space on MacOS, in Safari the single quote is replaced with a double quote and is shown like this:

<img width="1093" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/5093679/69d64bdb-768a-40a8-8ebc-9501fe984f9e">

Whereas on Windows in Chrome it's encoding the inline style using single quotes:

<img width="1286" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/5093679/d539d3c6-0569-4107-b022-8ea0dc41dc6b">

This may look weird, but is [completely valid](https://www.w3.org/TR/html401/charset.html#h-5.3.2) because the browser will decode the entities before the style is passed to CSS, and in [CSS single and double quote characters](https://www.w3.org/TR/CSS2/syndata.html#strings) are valid.

**Going back to the original issue, our Reveal component doesn't support fallback fonts. This means you should be setting the single font of "AvenirNextLTPro", and not "AvenirNextLTPro, sans-serif". When you're using the type containing the fallback internally Reveal is trying to use that entire string as the font name, which will obviously fail and resort to a generic font.**

I'll close this issue, if you have further questions or would like to reopen this issue, let us know.

**Closed by TorreyBetts** 2023-09-13 15:05 UTC
Labels: :bug: bug, :clock11: status: awaiting-development

**Comment by TorreyBetts** [comment] 2023-09-18 14:08
I reworked the implementation to solve the issue. The fix will appear in the next release.

**Comment by dwilches** [comment] 2023-10-16 20:43
Thanks!
