### ISSUE TITLE
[BUG]: "Process Data on Server" option not presented when adding field from another data source (data blending)

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#101] opened 2023-10-04 14:40 UTC
### SDK Version

1.6.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

I have a visualization with a SQL Server sproc data source. When joining to a second sproc data source, the "Process Data on Server" option is not presented on the joined sproc. As such, the AdditionalTable in the rdash file always gets saved with ServerAggregation=true.

I can create a visualization in Slingshot with multiple sprocs joined together and even with this bug occurring, I can still use functions that are normally disabled when "Process Data on Server" = true (e.g. fyear). However, when I export the .rdash file and load it into my application, the visualization does not load and shows an error:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/1265c08b-17aa-4652-9af3-7a87e116b7da)

I have tried manually setting ServerAggregation=false on the AdditionalTable in the .rdash file, but it makes no difference. It's as if that setting isn't being honored by the SDK and is always being treated as if it were the default value of "true".

I need to be able to use certain functions in my visualization, and therefore need the SDK to allow me to set "Process Data on Server" = false when performing data blending.

**Comment by brianlagunas** [comment] 2023-10-06 20:31
Tracked with internal issue AB#27166

**Comment by MLopezIG** [comment] 2023-10-09 19:49
Hi Amber. We've not been able to reproduce. When switching to Stored Procedures, the 'Process Data on Server' flag is made read-only but also is automatically turned off. Let me detail the steps I've tried:

Using Slingshot Web/Windows Desktop
1. Create a Sql Server datasource.
2. Choose a stored procedure (note that the flag is turned off automatically)
3. Fill any required parameters
4. In the visualization editor choose +/"Fields from another Data Source"
5. Choose a stored procedure (again, the flag is turned off automatically)
6. Fill any required parameters and accept
7. Select fields for joining
8. Add a new calculated field using 'fyear([field from blended source])'.
9. Use the calculated field in the pivot, check it works
10. Export the dashboard as 'rdash', unzip & open the Dashboard.json file, check that there's no "ServerAggregations": true anywhere. 

Would you mind sharing with us the steps to reproduce your issue?

**Comment by agroton-libtax** [comment] 2023-10-09 21:32
I asked our SAS dev (who creates our dashboards in Slingshot) to run through this process to see if he can reproduce with a fresh dashboard, and take screenshots. I attached his steps to reproduce (as well as the resulting .rdash file), and he included notes where what he saw didn't match up with what you stated. His resulting test dashboard did have all "ServerAggregation" nodes set to "false", but when I add it to our application, it still presents the "fyear not supported" error. We are using Slingshot for Windows 1.0.2861.0.
[Test - Joined SPROC.zip](https://github.com/RevealBi/Reveal.Sdk/files/12850737/Test.-.Joined.SPROC.zip)

**Comment by MLopezIG** [comment] 2023-10-09 22:35
Great! The screenshots gave us a hint: You only have Stored Procs available in your database. That's the difference between your environment and ours. In ours, we have Tables + Views + stored procs. The screen initially shows Tables, and when you go to the SProcs tab, the flag is turned off. The bug is, then, that the flag is not correctly initialized when that's the first screen. 

As you already figured out, the workaround is making sure that the flag is turned off, even in the scenario you describe where the stored procs parameters screen cover the checkbox. That's what should be done until we fix/improve how that works. 

However, looks like taking care of that flag is still not helping you with the 'fyear'. That's still something we cannot reproduce. Creating the dashboard as you described, exporting it and opening it in a standard SDK, works for us. 

Is it possible that you're changing the flag value in the IRVDataSourceProvider implementation, or maybe you're doing changes to the dashboard JSON?

**Comment by agroton-libtax** [comment] 2023-10-10 15:55
Eureka, it is now working for us! I had to set ` ProcessDataOnServer = false` in the IRVDataSourceProvider implementation. I had tried this before when we chatted about it, but I believe I only set it on the joined data source that had `ServerAggregation=true` in the json. I did not think to set it on the other data source (the one with `ServerAggregation=false`), because I didn't realize that the SDK defaults `ProcessDataOnServer= true` when you implement IRVDataSourceProvider, and the visualization worked fine when it was using only that data source.

That being said, I'm not sure how the visualization worked before we added the join, since it used fyear() and the IRVDataSourceProvider appears to have been setting `ProcessDataOnServer=true`?

Anyway, this is no longer a critical bug for us, and now that we see the "process on server" checkbox is just unintuitively hidden behind the stored proc params screen, this is merely a user-friendliness issue.

**Comment by MLopezIG** [comment] 2023-10-10 16:08
From what you say, you're getting ProcessDataOnServer == true in the RVDatasourceItem parameter of changeDataSourceItem?

**Comment by agroton-libtax** [comment] 2023-10-10 16:49
No, I completely replace the data source item with a newly constructed one like so:

IRVDataSourceProvider:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/64871e35-396c-4fbb-8201-4fbe90a0c94e)

SqlServerDataSourceFactory:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/cffe1179-21ae-4fbf-822c-9036da8371f9)
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/081b0a8d-2c15-4f5b-a495-3ba42b7d7b6e)

The only change I made was to set `ProcessDataOnServer=false` because I didn't realize that if you don't set it, it defaults to True.

**Comment by MLopezIG** [comment] 2023-10-10 17:16
Awesome, all pretty clear right now. 

The SDK needs at least these two fixes:
1. The 'Process Data On Server' flag is incorrectly turned on for Stored Procs if there are no Tables or Views in the database. It is also a mistake that it is not readonly.
2. When blending, we need to keep consistency in the PDS flag value (all of the sources must have it turned off, or all of them turned on).

I think we should close this issue, as it was a UX issue plus the missing ProcessDataOnServer = false line. 
If you're interested in tracking progress of any of the two issues mentioned before, then please create separate issues (we'll link them to the internal ones).

**Comment by brianlagunas** [comment] 2023-10-16 14:18
As noted above, we are closing this issue. If you still need assistance on this issue, pleaase feel free to comment and we can reopen if necessary.

**Closed by brianlagunas** 2023-10-16 14:18 UTC
Labels: :bug: bug, :clock11: status: awaiting-development

**Comment by MLopezIG** [comment] 2023-10-23 22:29
> Awesome, all pretty clear right now.
> 
> The SDK needs at least these two fixes:
> 
> 1. The 'Process Data On Server' flag is incorrectly turned on for Stored Procs if there are no Tables or Views in the database. It is also a mistake that it is not readonly.
> 2. When blending, we need to keep consistency in the PDS flag value (all of the sources must have it turned off, or all of them turned on).
> 
> I think we should close this issue, as it was a UX issue plus the missing ProcessDataOnServer = false line. If you're interested in tracking progress of any of the two issues mentioned before, then please create separate issues (we'll link them to the internal ones).

A note about these too: they seem to be a problem just for Slingshot, couldn't reproduce in the SDK with 1.6.1
