### ISSUE TITLE
Unexpected tooltip positioning

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#29] opened 2023-04-27 18:04 UTC
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

While hovering the blue column in this image, notice the location of the tooltip (purple areas are redacted), it's quite far from the column I was hovering:

![image](https://user-images.githubusercontent.com/3975401/234952031-c0fbba02-08fd-4605-a811-5a722443446e.png)

I have not seen the issue in other graphs, so the issue may be all these columns are under the same label "2023", but different categories, and Reveal is locating the toltip not on the hovered column but on the whole "cell". This is how the configuration looks:
![image](https://user-images.githubusercontent.com/3975401/234952812-767e44a2-5195-4ed7-b450-35983ddf821f.png)

**Comment by brianlagunas** [comment] 2023-04-27 18:18
Technically this is "by design", so I am changing this to a "feature Request". However, we are in the middle of an effort to change how the tooltips work to improve this experience.

We are moving to a hover-based tooltip, so you no longer have to click on the visualization to see the tooltip actions. Along with this is improving the tooltip positioning.  We are tracking this work with internal ID AB#20184.

In the v1.5 release next week, the WPF SDK will have this new tooltip behavior as a beta feature. Adding this new behavior to the web SDK is scheduled for our next sprint.

**Comment by brianlagunas** [comment] 2023-08-04 14:49
This new and improved hover tooltip behavior will be available in this month's (Aug) release. Initially it will be turned off as we need to gather feedback on the new behavior before turning it on for everyone.

To turn on this behavior, set `$.ig.RevealSdkSettings.enableActionsOnHoverTooltip = true;`

Can't wait to hear what you think.

**Closed by brianlagunas** 2023-08-04 14:49 UTC
Labels: :toolbox: feature-request
