### ISSUE TITLE
Allow specifying dateFilterFrom/dateFilterTo in server-side export

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#25] opened 2023-04-19 18:08 UTC
**Is your feature request related to a problem? Please describe.**

I use code like this to export dashboards from the backend:

```java
RevealEngineInitializer.getDashboardExporter()
      .exportToPdf(dashboardId, tempPath.toString(),
                   userContext, new PdfExportOptions(),
```

But if the dashboard uses a data source that needs the `{dateFilterFrom}`/`{dateFilterTo}` placeholders, these will get always the value set in the dashboard at creation time.

**Describe the solution you'd like**

It would be nice to be able to pass the dates among the export options in the API.

**Describe alternatives you've considered**

For now we'll do a workaround that was mentioned in Discord about using the `userContext` and `RVDataSourceProvider` to replace the placeholders myself.

**Comment by MLopezIG** [comment] 2023-04-19 18:17
We should let users modify the dashboard and pass it to the export function. In this case, setting the dashboard's date filter should do the trick.

**Comment by MLopezIG** [comment] 2023-04-19 18:18
A workaround for the dateFilterFrom/dateFilterTo problem just mentioned is to set the range in the RVUserContext, and then do the replacements of the date placeholders in the IRVDataSourceProvider implementation.

**Comment by dwilches** [comment] 2023-05-10 15:15
@MLopezIG Thanks for the workaround information.

I finished implementing it and while testing it I noticed a limitation of the workaround. 

Notice in this image the date filter still says "Last 7 days", which would be misleading for a user, as the data shown by the charts is not consistent with what the date filter says (in this case, I set dateFilterFrom.To the last 24 hours):

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/81477191-c5a7-4fc4-93ec-9b6b8003ba17)

This is how the charts look in the UI, where "Last 7 days" shows the data between May 3 and May 10:

![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/36de3a62-f85a-4b78-84fa-026d2dfc4b6a)

Did I miss any step? Is there a way to remove that date filter from the PDF on server-side exports or somehow make it look consistent with the data?

**Comment by MLopezIG** [comment] 2023-05-10 15:29
I don't think you missed any step. The problem is in the workaround, it doesn't consider what the dashboard view header is displaying. I'm sorry you spend your time on it. 

The way to go is modifying the dashboard. With the current API, that's not as easy as it could get, b/c of two limitations:
1. Export only accepts a dashboardId, not the dashboard document, which is later resolved by your dashboard provider. You should figure out how to return the correctly modified dashboard. Maybe creating a temporary dashboard, register it with a generated, temporal ID so the IRVDashboadProvider returns it when requested.
2. we don't have public java API for the dashboard model (as we do have for C#, at least in beta). However, if this is a blocker for you, you can explore the json and make the changes on it.

I hope this helps.

**Comment by dwilches** [comment] 2023-05-10 19:46
This is indeed a blocker for us. But editing the dashboard ourselves is not a viable solution, it would make our system prone to breaking each time Reveal releases a new version, so we would depend on manual testing (which adds more load to ourselves and is prone to human errors). Also, it would hinder our ability to know what is a Reveal issue vs. our issue, as we are tampering with something we shouldn't.

**Comment by MLopezIG** [comment] 2023-05-10 21:06
Actually, you shouldn't need to make any special manual testing for each Reveal release. Here's why: Reveal must be able to read the dashboard file, since its storage is not managed by the SDK. So, in a way, the json format is 'public API' that we need to keep supporting. 

Even if we come up with a better, incompatible format in the future (note the 'FormatVersion' attribute in the dashboard json), we'll still need to handle dashboards in an old format. In this scenario, of a new format, you might be concerned of not being able to handle new dashboards, but such a change is expected to be properly announced in any release (so you can prepare your code appropriately).

**Comment by dwilches** [comment] 2023-11-08 20:41
Hello,

I'd like to know if there is advance in this feature request.

From the 2 proposed workarounds, the first one doesn't work because the date in the PDF and the date used to gather the data don't match:
![image](https://github.com/RevealBi/Reveal.Sdk/assets/3975401/67a97ef7-6f6d-45b0-9b46-e2819830ceec)

And, the second one, about modifying the dashboard's internal JSON manually, is lacking a public API we can use, so we could corrupt the dashboard if we tamper with data we are not supposed to.

Thanks.

**Comment by brianlagunas** [comment] 2023-11-08 21:02
There hasn't been any movement on this specific feature request, but it has come up in conversation today with regards to how we may be implementing the Server Side export of custom colors #34.

One idea we are playing around with now is exposing on the server some type of InitializeRevealScript property that would allow you to provide custom javascript to perform on the revealView instance that is created when performing a server side export.

```
PdfExportOptions options = new PdfExportOptions();
options.InitializeRevealViewScript = @" java script, or maybe a js file, goes here"

await _exporter.ExportToPdf(dashboardId, path, options);
```

Theoretically, if this works, you would be able to not only provide custom colors, but also set filters on the dashboard before the server export is performed.

Does this sounds like a solution you would be in favor of (assuming it works)?

**Comment by dwilches** [comment] 2023-11-08 22:19
Hi,
Sure, that solution sounds good to me,
Thanks!

**Comment by brianlagunas** [comment] 2023-11-09 15:27
Unfortunately, that solution didn't work out for the filtering.

**Comment by brianlagunas** [comment] 2023-11-15 15:55
Okay, we have a temporary solution to unblock you. This is the API we are adding to control the filters

<img width="759" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/835562/f67785ca-141e-45cb-a414-c1024b85fe0d">

This is somewhat limiting, but does allow you to change any of the filters in your dashboard. In the future, we will most likely do away with this API in favor of an approach where you can modify the dashboard directly and then pass the dashboard instance into the exporter to be exported. This will be much more flexible and open a number of customizable solutions.

However, we don't have time for to implement that now and we didn't want to make you wait for that new API to implemented, so we exposed these properties for you to get you up and running with exporting.

**Comment by dwilches** [comment] 2023-11-15 16:50
Thanks you for looking into this. 
Is that `options` object the PdfExportOptions?
And I see the screenshot is for C#, will it also be available for the Java SDK?

**Comment by brianlagunas** [comment] 2023-11-15 17:03
The API will be on the base options object so all option types will have it. Yes, it will be available in Java.

**Comment by dwilches** [comment] 2023-11-15 17:06
Sounds good, thanks!

**Closed** 2023-12-01 23:49 UTC
Labels: :toolbox: feature-request, :white_check_mark: status: resolved
