### ISSUE TITLE
[BUG]: Export row count is not matching

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#76] opened 2023-08-31 14:36 UTC
### Company

IMSPOS

### SDK Version

1.4

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Description

Hi, 
We are finding discrepancy in record counts that we are exporting and actual record count. Please find below screenshots for more details . We are using SQL Server datasource

![image](https://github.com/RevealBi/Reveal.Sdk/assets/89643622/70055e90-8e1c-4a62-bc5a-ba7531b1a68c)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/89643622/f9f78b97-267c-4eb3-8b5e-474656d2025c)

![image](https://github.com/RevealBi/Reveal.Sdk/assets/89643622/6d158691-6abd-4252-bbf5-ba5be7aed46e)

**Comment by Christianig** [comment] 2023-08-31 15:04
Hi, you reached the 100k cells limit on the view, so you are exporting those 50k rows (2 fields 50k = 100k cells).

**Comment by vishwa-ims** [comment] 2023-08-31 15:06
Hi , Then how to export all the rows because actual row count is lot more than 100k

**Comment by Christianig** [comment] 2023-08-31 15:34
Let me research about this. Is this a web solution? which SDK are you using? asp.net, java or node-js?

**Comment by vishwa-ims** [comment] 2023-08-31 17:20
Yes it's web solution and we are using asp.net SDK

**Comment by Christianig** [comment] 2023-08-31 17:24
You can use this workaround, in the client to increase the limit of the cells on the view, adding this line:

$.ig.RVUtility.prototype.maxCellsRestriction = 2000000;

 but this is totally discouraged because might lead to issues and slowdowns.

**Comment by brianlagunas** [comment] 2023-08-31 17:30
Are you expecting the exported data to match the data in the tables of the database? If so, this is not a bug. The exported data is not the raw data. It will be the data after it has been grouped, aggregated, and with other applied transformations that visualization needed to perform in order to properly visualize it.

**Comment by vishwa-ims** [comment] 2023-08-31 17:46
What we are expecting is that whatever data which is displayed on visualisation after grouping and after applying filter should get exported as it is . This is correct expectations, right ?

**Comment by vishwa-ims** [comment] 2023-09-01 02:59
Yes . But that is not getting exported . Total records count after filter is around 700k . On visualisation it is showing 100k and when I export it , it only showing 50k after export

**Comment by Christianig** [comment] 2023-09-01 11:42
Hi, that is due to the first comment I did to this issue, there is a 100k limit visualization on the widgets to prevent slowdowns on the UI.

**Comment by brianlagunas** [comment] 2023-09-01 15:42
I am closing this as it is not a bug. You are hitting the 100K cell limit of the Reveal SDK. Keep in mind, 100K cells does not equate to data rows. You can use the work-around given in the comment above to increase this limit at the risk of introducing UI performance degradation.

**Closed by brianlagunas** 2023-09-01 15:42 UTC
Labels: :bug: bug

**Comment by brianlagunas** [comment] 2023-09-01 16:31
No, the export will only contain the data that is used in the visualization.

**Comment by vishwa-ims** [comment] 2023-09-01 16:58
Hi Brian,

In this case , I am having 700k rows in database(after filter) , visualization is showing 100k and after export I am getting 50k rows.

Is this something expected behavior ?

regards,
Vish
________________________________

**Comment by brianlagunas** [comment] 2023-09-01 17:07
To be clear, the visualization is limited to 100K **cells**, not rows. In your example, the grid is made up of two columns (2 cells each row). Since the visualization is limited to 100K cells, this means the number of rows in your grid is only 50K. Only 50K rows will be exported.

The message you see is not telling you that you are seeing 100K rows, it is telling you are seeing 100K cells. This message needs to be improved to be more clear. I can see how it can cause some confusion.

**Comment by vishwa-ims** [comment] 2023-09-01 17:19
Thank you Brian for the clarification.

regards,
Vish
________________________________

**Comment by PVillarmarzo** [comment] 2023-09-06 14:01
I'm sorry, but it's not possible because of the way the SDK is designed.
