### ISSUE TITLE
[BUG]: Dividing values doesn't show decimals in pivot tables if you use pre-calculated fields

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#45] opened 2023-06-06 18:53 UTC
### Company

Casebook

### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Steps to recreate:
1. Create a visualization with a number in a pivot table.
2. Create a pre-calculated field and divide that number by something else (in my case I did [interaction_duration]/3)
3. Add this to rows and/or values

### Actual Results:
Even when you add decimals it shows a whole number rounded down to the nearest integer. (ex. 11/6 = 3)

### Expected Results:
When you divide you should be able to see the decimals.

### Current workarounds:
1. If you add the number (ex. [interaction_duration]) to the rows and then create a post-calculated field and put it in Values it will show the decimals.
2. If you convert your visual to a Grid it will display the decimals.

**Comment by Christianig** [comment] 2023-06-07 16:21
Hello, thanks for your report.
We cannot reach the issue with the steps provided. 

In more detail, we were following these steps:

1. Adding a new visualization (using an excel file)
2. Selecting a pivot
3. Add a calculated field with expression "11/3"
4. Drop the field to pivot rows (check 0 decimals)
5. Change decimals to show 2 places

The decimals are shown as expected.
Are we missing some other step on the reproduction? 

Note that dropping fields to values, should aggregate the value as sum as default. To see the actual value, you can aggregate it as min for example.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/14891077/eb4745f1-bec7-4851-bde1-ad4bcb28dd06)

**Comment by gauxgaux** [comment] 2023-06-08 17:44
I didn't do the calculation with two numbers. I was using a field and a number. So [open]/3 or something like that.

**Comment by Christianig** [comment] 2023-06-08 18:27
We tried here both scenarios, here in the image you can see a pre-calculated field with and without decimals for the expression [open]/3.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/14891077/c6f0b2b3-5a90-4591-aae7-3536e384a3de)`

And here using just the rows 
![image](https://github.com/RevealBi/Reveal.Sdk/assets/14891077/6ac2d6bd-df7e-4f1c-a362-c13cfc8bc289)

Both scenarios are showing decimals correctly.
Other scenario tried is using a nested calculated field like this:
Calculated1: [open]
Calculated2: Calcualted1/3

In both cases when the decimals places are set to 2, it shows the figures.

Tried on Excel data source. May I ask the kind of data source you are using?
Any other consideration?

**Comment by brianlagunas** [comment] 2023-07-25 14:16
@gauxgaux is this still an issue for you? As you can see, we have been unable to duplicate the issue. Can you provide answers to the follow-up questions so we can continue to look into this?

**Comment by brianlagunas** [comment] 2023-08-04 14:22
I am closing this since we have been unable to duplicate this issue and there has been no further activity. If this is still an issue, please comment with more information and we will reopen.

**Closed by brianlagunas** 2023-08-04 14:22 UTC
Labels: :bug: bug, :eyes: status: in-review
