### ISSUE TITLE
[BUG]: Unable to click text "X Selected"/"Show All" on a filter

### ISSUE THREAD

**Issue by exscalliber** [RevealBi/Reveal.Sdk#60] opened 2023-07-19 02:05 UTC
### Company

N/A

### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Node.js

### Description

When trying to switch between what is selected and what available filters there are, you must click just outside of the text on a filter.

Example image: 

![Screenshot 2023-07-19 at 1 48 56 PM](https://github.com/RevealBi/Reveal.Sdk/assets/75103473/34716e59-d16d-462f-9665-c98ac61cbb17)
I cannot press the button inside the red box. I can if my cursor is just outside of the text. It seems as though pointer-events are disabled for the text.

I did this on the developer playground (https://help.revealbi.io/playground/ -> load dashboard)

Also, as a side note/Feature request: it would be great if there was some sort of colour-change/onHover/Border on that button so its obvious it is a button. Currently it just looks like some informational text.

**Comment by Christianig** [comment] 2023-07-20 12:04
Thanks for reporting this issue. We are going to evaluate internally the scenario. The issue is tracked on our internal system on the item AB#25635.

**Comment by TorreyBetts** [comment] 2023-07-31 11:51
This issue has been fixed and will be released in an upcoming release.

**Closed by TorreyBetts** 2023-07-31 11:51 UTC
Labels: :bug: bug, :white_check_mark: status: resolved
