### ISSUE TITLE
[BUG]: Export to PDF not working

### ISSUE THREAD

**Issue by vishwa-ims** [RevealBi/Reveal.Sdk#79] opened 2023-09-07 14:47 UTC
### SDK Version

1.5

### Client Framework

ASP.NET Web App

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Hi ,
When we try to export visualisation to PDF then it is not working and just keep on loading . But export to excel is working fine . 

Below is error that we receive when we try to export as pdf

<img width="1353" alt="Screenshot 2023-09-07 at 8 14 55 PM" src="https://github.com/RevealBi/Reveal.Sdk/assets/89643622/06687d3e-2ed1-453a-a9a7-bed81d905379">

**Comment by brianlagunas** [comment] 2023-09-07 14:52
Have you tested this on a newer version like 1.5 or 1.6?

**Comment by vishwa-ims** [comment] 2023-09-07 14:55
Sorry , by mistake I have mentioned 1.4 . Actually we are using 1.5 so yes it is observed on 1.5

**Comment by brianlagunas** [comment] 2023-09-07 15:02
PDF export is working for me 
![image](https://github.com/RevealBi/Reveal.Sdk/assets/835562/bbe8e339-9ebf-442b-8813-ce560738a32a)

Do you see an actual error message anywhere? Can you check your logs or the console? Does it work locally during debug for you?

**Comment by vishwa-ims** [comment] 2023-09-07 15:07
When I check console I can see that "tools/renderhtml/" call is failing with below error

System.Exception: Timeout when taking screenshot, more than 2 threads were being executed
   at Infragistics.EMServer.Web.Controllers.WebAPI.SdkToolsController.RenderHtml(IExportToolService service)
   at lambda_method730(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by brianlagunas** [comment] 2023-09-07 15:10
@gkaveckis any idea what this could be? I cannot duplicate it.

@PVillarmarzo can you log this bug in our internal system?

**Comment by brianlagunas** [comment] 2023-09-07 15:18
Maybe try increasing the `RevealEmbedSetting.Export.ExportingTimeout ` property. The default value is 3000ms.

**Comment by vishwa-ims** [comment] 2023-09-07 15:39
I tried it by setting value to 500000 but it is still failing

**Comment by gkaveckis** [comment] 2023-09-07 16:44
> @gkaveckis any idea what this could be? I cannot duplicate it.
> 
> @PVillarmarzo can you log this bug in our internal system?

Hi, 
if only excel is working seems it is related to images generation, as it was mentioned before... there should be an an extra log information with more concrete data.

If you are running it locally please check the console output from the server

**Comment by gkaveckis** [comment] 2023-09-11 14:05
Hi @vishwa-ims 
Did you have a chance to test 1.6 version?

**Comment by vishwa-ims** [comment] 2023-09-13 12:37
Hi @gkaveckis 
We are trying to upgrade version to 1.6 but facing couple of issues . We are getting namespace not found error for "Reveal.Sdk.Data.Microsoft.SqlServer" . Not sure if I am missing anything . I already updated server side package to 1.6

**Comment by TorreyBetts** [comment] 2023-09-13 13:01
> Hi @gkaveckis
> We are trying to upgrade version to 1.6 but facing couple of issues . We are getting namespace not found error for "Reveal.Sdk.Data.Microsoft.SqlServer" . Not sure if I am missing anything . I already updated server side package to 1.6

Did you review the [release notes](https://help.revealbi.io/web/release-notes#aspnet) before updating? Data sources have been extracted out into separate packages and need to be registered.

**Comment by vishwa-ims** [comment] 2023-09-14 12:56
> > Hi @gkaveckis
> > We are trying to upgrade version to 1.6 but facing couple of issues . We are getting namespace not found error for "Reveal.Sdk.Data.Microsoft.SqlServer" . Not sure if I am missing anything . I already updated server side package to 1.6
> 
> Did you review the [release notes](https://help.revealbi.io/web/release-notes#aspnet) before updating? Data sources have been extracted out into separate packages and need to be registered.

Hi

I was able to install required package but now when I am trying to load existing dashboards then I am getting below error

<img width="1412" alt="image" src="https://github.com/RevealBi/Reveal.Sdk/assets/89643622/7c7f43af-ec5b-41de-973c-981e7968e1c3">

**Comment by gkaveckis** [comment] 2023-09-14 13:03
> > > Hi @gkaveckis
> > > We are trying to upgrade version to 1.6 but facing couple of issues . We are getting namespace not found error for "Reveal.Sdk.Data.Microsoft.SqlServer" . Not sure if I am missing anything . I already updated server side package to 1.6
> > 
> > 
> > Did you review the [release notes](https://help.revealbi.io/web/release-notes#aspnet) before updating? Data sources have been extracted out into separate packages and need to be registered.
> 
> Hi
> 
> I was able to install required package but now when I am trying to load existing dashboards then I am getting below error
> 
> <img alt="image" width="1412" src="https://user-images.githubusercontent.com/89643622/267981273-7c7f43af-ec5b-41de-973c-981e7968e1c3.png">

Hi @vishwa-ims 

Did you register the data source?

` 
builder.Services.AddControllers().AddReveal( builder =>
{
//all data sources use the RegisterXXX naming convention
    builder.DataSources.RegisterMicrosoftSqlServer();
});
`
Please find more details here: https://help.revealbi.io/web/datasources/

**Comment by vishwa-ims** [comment] 2023-09-14 14:48
Hi,
PDF export  issue is still present in V1.6

Below is error response from renderhtml

System.Exception: Timeout when taking screenshot, more than 2 threads were being executed
   at Reveal.Sdk.PlaywrightBrowser.PageFactoryHelper(Func`2 factory)
   at Reveal.Sdk.PlaywrightBrowser.TakeScreenshot(String html, Int32 pageHeight, Int32 pageWidth)
   at Reveal.Sdk.ExportToolService.DoTakeScreenShotAsync(String html, Int32 width, Int32 height)
   at Infragistics.EMServer.Web.Controllers.WebAPI.SdkToolsController.RenderHtml(IExportToolService service)
   at lambda_method670(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by vishwa-ims** [comment] 2023-09-25 13:24
@gkaveckis  @brianlagunas  do you have any updates on this ?

**Comment by vishwa-ims** [comment] 2023-09-26 13:56
@gkaveckis  We are using ASP.NET core . Do you have sample code with UI so we can test it ? I can see you have only angular and react example for client side. Server side only contains API calling in your example . But I think that might not match with our usecase

**Comment by vishwa-ims** [comment] 2023-09-27 13:48
@brianlagunas  I tried to create a sample project . Please use below git repo to download source code .

May be you need to configure SQLSERVER datasource to create visualisation and try export to PDF

https://github.com/ims-pos/reveal-sample-code/tree/V1.6

**Comment by vishwa-ims** [comment] 2023-10-05 14:57
@brianlagunas  It is observed that export to pdf is working when we run code in localhost but when we are publishing it on server with iis , it is not working . Do we need to give any specific permissions or any specific setup needed on server ?

**Comment by brianlagunas** [comment] 2023-10-05 16:55
@vishwa-ims have you verified Playright is installed as mentioned in this topic: https://help.revealbi.io/web/configure-export#aspnet

**Comment by vishwa-ims** [comment] 2023-10-10 14:01
@brianlagunas  I confirmed that Playwright is installed and also I have added package in my project to make sure it will not take loading time to install while we are browsing the dashboards . But still it is not working

**Comment by brianlagunas** [comment] 2023-10-10 14:18
@vishwa-ims can you create a Docker container that can duplicate the issue? We cannot duplicate it. We have tried everything we can think of. There is something on specific on your server causing the issue. Unfortunately, without the ability to duplicate the issue, we are unable to help.

**Comment by brianlagunas** [comment] 2023-11-07 15:39
I am closing this issue as we have been unable to reproduce the issue. If you are able to provide a VM or Container that can create an environment that reproduces the issues, we can reopen.

**Closed by brianlagunas** 2023-11-07 15:39 UTC
Labels: :bug: bug, :eyes: status: in-review
