### ISSUE TITLE
[BUG]: Issue when using Google charts and Reveal.

### ISSUE THREAD

**Issue by federicoprovera** [RevealBi/Reveal.Sdk#66] opened 2023-08-16 13:23 UTC
### Company

Infragistics

### SDK Version

1.3.1

### Client Framework

Angular

### Server Platform

ASP.NET

### Description

Customer reports:

"We just discovered a problem - the Reveal js script is breaking some of our non-Reveal code, specifically these donut charts. The first video illustrates current behavior, and the second video illustrates how it used to work before adding Reveal (I commented out the infragistics.reveal.js script in index.html and $.ig.RevealSdkSettings.setBaseUrl/setAdditionalHeadersProvider code). Front end arch is Angular Typescript and the donut charts are dependent on angular-google-charts 2.2.3 npm package. Anyone have any ideas or workarounds to fix this?"

We were able to reproduce the issue.  When creating a couple pie charts using Google Chart and hovering over the slices in the bottom, it fails with the following error:

zone.js:182 Uncaught RangeError: Maximum call stack size exceeded
    at gvjs_0e (jsapi_compiled_default_module.js:70:17)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)
    at gvjs_0e (jsapi_compiled_default_module.js:70:413)

Steps for reproduce:

1) Create an angular client app, as described here: https://help.revealbi.io/web/getting-started-angular/

2) Install google charts with npm, as described here: https://www.npmjs.com/package/angular-google-charts/v/2.2.3

3) Use this index.html:

<html>
  <head>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data1 = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     5],
          ['Eat',      5],
          ['Commute',  5],
          ['Watch TV', 5],
          ['Sleep',    4]
        ]);

        var data2 = google.visualization.arrayToDataTable([
          ['Employee', 'Fees'],
          ['Emp1', 25],
          ['Emp2', 25],
          ['Emp3', 25],
          ['Emp4', 25],
          ['Emp5', 25]
        ]);

        var options1 = {
            title: 'Hours in a day',
            legend: 'none' // Hides the Legend.
        };

        var options2 = {
            title: 'Employees fees',
            legend: 'none' // Hides the Legend.
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data1, options1);

        var chart2 = new google.visualization.PieChart(document.getElementById('piechart2'));

        chart2.draw(data2, options2);
      }    

    </script>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet" type="text/css">    

  </head>
  <body>
    <app-root></app-root>
    <div id="piechart" style="width: 450px; height: 250px;"></div>
    <div id="piechart2" style="width: 450px; height: 250px;"></div>
     <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
    <script src="https://dl.revealbi.io/reveal/libs/1.3.1/infragistics.reveal.js"></script>
  </body>
</html>

4) Use this app/app.component.html

<div #revealView style="height: 100vh; width: 100%; position:relative;"></div>

5) Use this app/app.module.ts

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { GoogleChartsModule} from 'angular-google-charts'

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    GoogleChartsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

6) Run the application with ng server --open

7) Opening the browser inspect, hover on the google charts until they fail with the error described above.

**Comment by brianlagunas** [comment] 2023-08-18 15:36
Tracked with internal issue AB#26260

**Comment by TorreyBetts** [comment] 2023-09-15 19:57
Hi!

We have found the cause of the issue and unfortunately it's out of our hands, although I have created a workaround. Reveal extends some of the native prototypes in JS to add additional features and enhance functionality. Google Charts didn't appear to account for developers extending the JS prototypes and the result is a cyclic reference within their code when they clone objects and iterate through properties.

To workaround this issue, you'll need to pin a version so function name changes don't affect your code. In this workaround code I used version 51.

`google.charts.load('51', { 'packages': ['corechart'] });`

The monkey patch workaround is as follows. I'll include TypeScript as well as JavaScript so that you can take advantage of either place you may want to use it in your Angular app.

### TypeScript

```TypeScript
    window.gvjs_0e = function(a: any): any {    
        if (typeof a !== 'object' || a === null) {
            return a;
        }
    
        if (typeof a.clone === 'function') return a.clone();
        if (typeof Map !== 'undefined' && a instanceof Map) return new Map(a);
        if (typeof Set !== 'undefined' && a instanceof Set) return new Set(a);
    
        const isArray = Array.isArray(a);
        let b: any = isArray ? [] : {};
    
        for (let c in a) {
            if (a.hasOwnProperty(c)) {
                b[c] = window.gvjs_0e(a[c]);
            }
        }
    
        return b;
    }; 
```

### JavaScript

```JavaScript
window.gvjs_0e = function(a) {    
    if (typeof a !== 'object' || a === null) {
        return a;
    }

    if (typeof a.clone === 'function') return a.clone();
    if (typeof Map !== 'undefined' && a instanceof Map) return new Map(a);
    if (typeof Set !== 'undefined' && a instanceof Set) return new Set(a);

    const isArray = Array.isArray(a);
    let b = isArray ? [] : {};

    for (let c in a) {
        if (a.hasOwnProperty(c)) {
            b[c] = window.gvjs_0e(a[c]);
        }
    }

    return b;
};
```

The magic of the fix is the `hasOwnProperty` usage as it helps skip over properties that were added to the prototype. 

With this reply I'll close this issue. Feel free to reply if you have further questions.

**Closed by TorreyBetts** 2023-09-15 19:57 UTC
Labels: :bug: bug, :clock11: status: awaiting-development

**Comment by gary-calpo-lts** [comment] 2023-09-19 14:33
@TorreyBetts Good morning.  We used your workaround to resolve the Google Charts issue in our app.  Thank you!
