### ISSUE TITLE
[BUG]: Timezone Calculations not working when there are joins in a dataset

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#131] opened 2023-11-28 18:09 UTC
### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Operating System

Linux

### Description

When using the functions `applytimezone({date}, currenttimezone())` with no joins the functions work, when you join an additional dataset it stops working.

**Comment by gkaveckis** [comment] 2023-11-29 16:05
Hi @gauxgaux 
Just to understand better the case, is that {date} field parte of the orginal dataset or is member of the joined one.
Another question, which is the datasource used in this example.

Thanks

**Comment by gauxgaux** [comment] 2023-11-29 16:41
Hi @gkaveckis - no, the {date} field listed is intended to represent any date field you want to use. I tried it with multiple kinds from multiple datasets.
We use redshift for our datasource.

**Comment by gkaveckis** [comment] 2023-11-30 14:49
Hi @gauxgaux 
I've been working on this issue and It is being hard to reproduce it, but let me share the example I made to validate with yours
![image](https://github.com/RevealBi/Reveal.Sdk/assets/15742749/ec04acc4-110b-4973-9252-3cd3409043be)

Some additional information that might be helpful
 When you said it didn't work.. the application display the date without applying the time zone or an empty value is displayed?
 Do you receive any error?
What happens if you create a calculated field with just the result from currenttimezone() function? it displays something? 
Also which browser are you using?.. with other browser happens the same?

Is this issue also happening enabling/disabling the Process Data on Server flag?

Thank for your help

Regards.

**Comment by dpazos-infragistics** [comment] 2023-12-11 16:07
Hi, @gauxgaux, it's been a while since we last heard from you.
Could you get this sorted out?
Let us know if we can be of any further assistance.

**Comment by gauxgaux** [comment] 2023-12-12 16:45
Hi! Sorry for the delay. Here's some more deets:

> When you said it didn't work.. the application display the date without applying the time zone or an empty value is displayed?

It displays and shows no error but the timezone is the same is unchanged. So if you display the original date field next to the new one it shows both in GMT.

> Do you receive any error?

Nope, no error, just incorrect time.

> What happens if you create a calculated field with just the result from currenttimezone() function? it displays something?

Good idea! When I add currenttimezone() and display it, it shows `America/Los_Angeles` when there's no join. When I join and refresh it shows `Etc_UTC`. 

> Also which browser are you using?.. with other browser happens the same?

I've been using chrome but when I switch to Safari it has the same behavior

> Is this issue also happening enabling/disabling the Process Data on Server flag?

I don't know about this one - I have the question out to my dev.

**Comment by gauxgaux** [comment] 2023-12-12 17:24
Sounds like for the `enabling/disabling the Process Data on Server flag` it's not applicable for Redshift.

**Comment by dpazos-infragistics** [comment] 2023-12-12 17:35
We tried to replicate this behaviour where currenttimezone() shows Etc_UTC for you but we have been unable to do so.
Can you provide us with an .rdash that reproduces the problem using one of the datasource from Reveal's samples?

**Comment by gauxgaux** [comment] 2023-12-12 19:44
Can you point me in the right direction to do that? I could provide an rdash with our dummy data or send a video.

**Comment by dpazos-infragistics** [comment] 2023-12-12 20:05
Your team probably implemented a DashboardProvider that saves the dashboards to some storage of your own.
Check that, and once you determine where they are being stored, you should be able to create a sample dashboard and get the corresponding .rdash from there.

**Comment by gauxgaux** [comment] 2023-12-12 20:24
[36302611-33f8-4681-b01a-78572187bb76.rdash.zip](https://github.com/RevealBi/Reveal.Sdk/files/13652918/36302611-33f8-4681-b01a-78572187bb76.rdash.zip)

**Comment by dpazos-infragistics** [comment] 2023-12-12 20:29
Thanks. We'll be looking into it.

**Comment by dpazos-infragistics** [comment] 2023-12-12 20:34
I see you sent us your own dashboard, which is linked to your own instance of Redshift.
Since we don't have access to that, I can't load up the visualization.
Is there any chance that you can create a small sample showing the Etc__UTC value for getcurrenttimezone() using one of the datasources from the Reveal samples?

**Comment by gauxgaux** [comment] 2023-12-12 20:48
I don't know where you're talking about. I know the steps to recreate but I don't know where I would connect to Reveal Samples. Do you have a link or demo I can go on to try and recreate?

**Comment by dpazos-infragistics** [comment] 2023-12-12 21:09
I tried analyzing the file and trying to recreate it by hand but we're encountering a restriction that doesn't allow me to do it.
Is there any chance that you can create a video showing how you're defining the visualization that causes the error?

**Comment by gauxgaux** [comment] 2023-12-13 17:05
[Here's a link](https://drive.google.com/file/d/1jOtQyZjk81YXOCQ0dCX4YTGsQ3Uw_rFt/view?usp=sharing) to a screen recording.

**Comment by dpazos-infragistics** [comment] 2023-12-13 18:35
Thank you. I'll look into it and try to reproduce the issue.

**Comment by dpazos-infragistics** [comment] 2023-12-13 19:25
I tried reproducing your scenario and could not have the error occur.
What I did:
- Create a pivot visualization attached to a Redshift data source
- Add a string column and a date (minute) column to the Rows section of the visualization.
- Create a calculated column with applytimezone([date], currenttimezone()) and add it to Rows too.
- Add a field from another data source. Select the same Redshift data source as before, set the join by a numeric field. Select a text field.
- Refresh the data.

Also, adding the currenttimezone() field always shows the intended value, both with and without the calculated field.

Anything else you can think of that I could be missing?
I noticed you have a data filter set. What is that?

**Comment by gauxgaux** [comment] 2023-12-14 15:49
Yeah, I think you got the steps. The one note is that the currenttimezone() field changes depending on if there are no joins or one join. 

The data filter I have set is just to filter out empty start_date_involvement values, but I didn't notice any differences in it with our without the data filter.

**Comment by dpazos-infragistics** [comment] 2023-12-14 19:38
Do both of your data sources point to the same Redshift server?

**Comment by gauxgaux** [comment] 2023-12-14 20:21
Yep!

**Comment by nerzhei** [comment] 2023-12-21 16:04
We were able to duplicate the issue. An internal work item has been created to address it AB#28476.

**Comment by PVillarmarzo** [comment] 2024-01-17 13:13
This issue has been fixed and will be released in an upcoming release.

**Closed** 2024-01-17 13:14 UTC
Labels: :bug: bug, :white_check_mark: status: resolved

**Comment by brianlagunas** [comment] 2024-02-23 16:15
Yes, this is in our latest 1.6.4 release.
