### ISSUE TITLE
[BUG]: The same sorting value results in two different sort orders for different visualizations

### ISSUE THREAD

**Issue by rivadblins** [RevealBi/Reveal.Sdk#297] opened 2024-10-25 16:10 UTC
### SDK Version

1.7

### Client Framework

Other

### Server Platform

ASP.NET

### Operating System

Windows

### Description

When sorting by the "module" field which is the same for the two visualizations in the screenshot below, they get assigned the correct colour values but are not sorted properly on the UI.

![image](https://github.com/user-attachments/assets/deacb286-92b1-4d19-94b8-16780bea7de1)

**Comment by dpazos-infragistics** [comment] 2024-10-25 18:26
Hi. I tried to reproduce your scenario as closely as I could, but didn't encounter the issue.
The records I inserted into the test data are not in alphabetical order, and I didn't explicitly specify any sorting while creating the visualization, yet they came out sorted as expected.
Can you provide us with the rdash for further analysis?
![image](https://github.com/user-attachments/assets/50507551-99df-4f7d-885a-277a68cd45f3)

**Comment by dpazos-infragistics** [comment] 2024-10-25 19:56
Well, we tried the same scenario in 1.7.0 and we did face the same issue you're seeing.
It so happens that in release 1.7.0 the labels for the stacked bar are drawn in the incorrect order, while the bars follow the selected order.
The issue is fixed in our upcoming version 1.7.1 due next month.

**Comment by brianlagunas** [comment] 2024-10-25 20:09
The release is planned for the first week of Nov.

**Closed by brianlagunas** 2024-10-25 20:09 UTC
Labels: :bug: bug, :eyes: status: in-review
